# Generated by Django 5.2 on 2025-05-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Location',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['number'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='room',
            new_name='location',
        ),
    ]
